### ISSUE TITLE
시뮬레이션이 멈추는 현상 (OOM; out-of-memory ?)

### ISSUE THREAD

**Issue by JinraeKim** [JinraeKim/FTCTests.jl#22]
기동 = :hovering, random seed = 2022 일 때, (총 100개의 시뮬을 돌리게 했었나?) 18번째 case number 의 결과가 시간이 아무리 지나도 나오지 않음을 확인; 나중에 해당 시뮬 케이스에 이상이 있는지 검토해보아도 좋을듯

_Originally posted by @JinraeKim in https://github.com/JinraeKim/FTCTests.jl/issues/21#issuecomment-998073306_

**Comment by hnlee77** [comment]
정확하게 같은 현상이 일어나는 것으로 보아, 해당 시뮬케이스의 시간을 줄이거나 시뮬레이션을 강제로 멈춰 결과 그래프를 볼 수 있으면 좋겠어요.

**Comment by JinraeKim** [comment]
@seong-hun 의 조언에 따라, flush 를 중간중간 해주는 방식을 도입해야할수도 있겠음

**Comment by JinraeKim** [comment]
결과 그래프는 이미 볼 수 있습니다 (will_plot 옵션으로 저장시키면)

**Comment by JinraeKim** [comment]
몇 가지 실패 경우를 보았을 때, 고도가 추락하면서 DiffEq.jl 이 해를 잘 못 구해주는 것 같음. 콜백으로 특정 고도 이하가 되면 시뮬레이션을 종료하도록 할 예정
![image](https://user-images.githubusercontent.com/43136096/147045089-d2ecdf4a-b7f2-4fb0-a17d-c337297a20f8.png)
