### ISSUE TITLE
FDI delay 에 따라 고장률이 로터-비대칭적으로 나타나는 현상 발견

### ISSUE THREAD

**Issue by JinraeKim** [JinraeKim/FTCTests.jl#40]
@hnlee77 여기에 관련 그림 첨부 가능할까요?

**Comment by hnlee77** [comment]
전진비행 임무중 각 로터에 고장 발생시 평균 회복률
![image](https://user-images.githubusercontent.com/32696021/147434358-70b69ceb-25aa-4f23-bd8c-25c564888e35.png)
