### ISSUE TITLE
Empirical gramian 계산하는 함수 작성

### ISSUE THREAD

**Issue by hnlee77** [JinraeKim/FTCTests.jl#58]
### TODO
- [x]  Controllability gramian 계산 함수 작성
- [x]  Observability gramian 계산 함수 작성

**Comment by JinraeKim** [comment]
For linear system?

**Comment by JinraeKim** [comment]
Linear system 의 ctrl/obs gramian 부터 계산하기로 한 것 아니었나요?

**Comment by hnlee77** [comment]
> Linear system 의 ctrl/obs gramian 부터 계산하기로 한 것 아니었나요?

현재 짜놓은 코드를 좀만 더 살펴보다가 넘어가도록 하겠습니다ㅠ

**Comment by JinraeKim** [comment]
아 그럼요 그렇게 하세요 ㅎㅎ

**Comment by JinraeKim** [comment]
@hnlee77 관련 논문 또는 논문 링크 공유해주실 수 있을까요?

**Comment by hnlee77** [comment]
> @hnlee77 관련 논문 또는 논문 링크 공유해주실 수 있을까요?

[1] M. Tahavori and A. Hasan, “Fault recoverability for nonlinear systems with application to fault tolerant control of UAVs,” Aerosp. Sci. Technol., vol. 107, p. 106282, 2020, doi: 10.1016/j.ast.2020.106282.

**Comment by JinraeKim** [comment]
@hnlee77 논문을 오랜만에 다시 읽어봤는데, 꽤 흥미롭네요.

> [1] M. Tahavori and A. Hasan, “Fault recoverability for nonlinear systems with application to fault tolerant control of UAVs,” Aerosp. Sci. Technol., vol. 107, p. 106282, 2020, doi: 10.1016/j.ast.2020.106282.

여기서 인용중인, LTI 시스템 버전 ([N. E. Wu, K. Zhou, and G. Salomon, “Control Reconfigurability of Linear Time-Invariant Systems,” p. 5, 2000.](https://www.sciencedirect.com/science/article/pii/S0005109800000807?via%3Dihub)) 을 읽다가 궁금한 점이 생겼는데요.

Controllability Gramian `W_c` 와 observability Gramian `W_o` 가 있을 때, 이들의 minimum singular value 값이 "특정 상태로 보내거나, 관측하는데 필요한 에너지"와 관계된다고 표현되어있는데요. 이거 혹시 참고할 자료 있을까요?

![image](https://user-images.githubusercontent.com/43136096/150723813-be8f9ed9-4ee3-43fa-bd33-a7f55adec9cc.png)

별개로, 논문을 읽어보니 비선형이거나 LTV 이면 reconfigurability 계산이 어려운 것으로 보이네요.
cost 학습 대신 reconfigurability 를 학습하는 것도 좋은 연구 방향이 될 것이라고 생각합니다.
+) 어떤 파라미터 셋에서의 가장 작은 HSV (Henkel singular value) 를 control reconfigurability 로 표현하고 있는데, 이러한 control reconfigurability 를 쉽고 빠르게 계산하는 연구를 진행해도 좋을 것 같네요~

**Comment by hnlee77** [comment]
> > [1] M. Tahavori and A. Hasan, “Fault recoverability for nonlinear systems with application to fault tolerant control of UAVs,” Aerosp. Sci. Technol., vol. 107, p. 106282, 2020, doi: 10.1016/j.ast.2020.106282.
> 
> 여기서 인용중인, LTI 시스템 버전 ([N. E. Wu, K. Zhou, and G. Salomon, “Control Reconfigurability of Linear Time-Invariant Systems,” p. 5, 2000.](https://www.sciencedirect.com/science/article/pii/S0005109800000807?via%3Dihub)) 을 읽다가 궁금한 점이 생겼는데요.
> 
> Controllability Gramian `W_c` 와 observability Gramian `W_o` 가 있을 때, 이들의 minimum singular value 값이 "특정 상태로 보내거나, 관측하는데 필요한 에너지"와 관계된다고 표현되어있는데요. 이거 혹시 참고할 자료 있을까요?

이 부분에 대해서는 저도 조금 더 조사가 필요할 것 같습니다 ㅎㅎ 관련 참고자료를 찾게되면 공유합시다!

> 별개로, 논문을 읽어보니 비선형이거나 LTV 이면 reconfigurability 계산이 어려운 것으로 보이네요. cost 학습 대신 reconfigurability 를 학습하는 것도 좋은 연구 방향이 될 것이라고 생각합니다. +) 어떤 파라미터 셋에서의 가장 작은 HSV (Henkel singular value) 를 control reconfigurability 로 표현하고 있는데, 이러한 control reconfigurability 를 쉽고 빠르게 계산하는 연구를 진행해도 좋을 것 같네요~

일단 비선형시스템에서 구현자체가 꽤 어렵네요..ㅎㅎ 저도 그래서 이것을 학습하는 것도 좋은 연구방향이 될 것이라고 생각하고 있습니다. 추후 연구방향으로 생각해봅시다!
