### ISSUE TITLE
새로운 시뮬레이션을 수행 시, case number 가 덮어씌워지는 이슈

### ISSUE THREAD

**Issue by JinraeKim** [JinraeKim/FTCTests.jl#59]
메모리 이슈 등으로 인해 100개 정도씩 데이터를 뽑고 싶을 수 있는데, 매번 1에서 시작하는 번호로 데이터를 저장하기 때문에 궤적 데이터가 덮어씌워지는 버그가 있음.

@hnlee77 혹시 이를 어떻게 해결했었나요?

**Comment by hnlee77** [comment]
저의 경우에는 매번 100개의 데이터를 뽑고, 폴더를 매번 이동시킨 후 다시 데이터를 뽑았습니다. (까먹었을 땐 덮어써서 다시 뽑았음) 
제 생각에도 확실히 수정해야 할 이슈이긴 합니다. 데이터를 저장하는 폴더 이름을 `data`에서 `data_YYMMDD_hhmm`와 같이 현재 날짜, 시간등을 디렉토리 명으로 가져가는 거 어때요?

**Comment by JinraeKim** [comment]
> 저의 경우에는 매번 100개의 데이터를 뽑고, 폴더를 매번 이동시킨 후 다시 데이터를 뽑았습니다. (까먹었을 땐 덮어써서 다시 뽑았음) 제 생각에도 확실히 수정해야 할 이슈이긴 합니다. 데이터를 저장하는 폴더 이름을 `data`에서 `data_YYMMDD_hhmm`와 같이 현재 날짜, 시간등을 디렉토리 명으로 가져가는 거 어때요?

날짜, 시간으로 덮어쓰는 이슈가 해결될 수는 있겠습니다.

다만, "동일 데이터"가 중복되어 뽑히지 않도록 방지할 수 있는 장치가 필요할 것 같습니다.

특히, 현재 코드는 전체 시뮬레이션 개수 `N` 개만큼의 랜덤한 객체(예: 초기조건 등)를 미리 생성해놓고 병렬 시뮬레이션을 `N_thread` (<`N`) 개수만큼씩 뽑아서 돌립니다.
이러면 같은 seed 이더라도, `N` 에 따라 결과가 달라질 수 있겠습니다...

디렉토리 이름을 `data/data_seed_xxxxx_N_yyyy` 이런식으로 만들고, 데이터를 불러올 때 `data` 안의 모든 디렉토리로부터 불러오도록 할까요...?

**Comment by hnlee77** [comment]
흠 그렇군요. seed 와 시뮬레이션 갯수 `N`을 명시하여 디렉토리를 가져가는 것이 좋겠어요. 동의합니다~
