### ISSUE TITLE
Minimum Hankel Singular Value (HSV) 계산하는 함수 작성

### ISSUE THREAD

**Issue by hnlee77** [JinraeKim/FTCTests.jl#60]

**Comment by JinraeKim** [comment]
LTI 시스템 버전을 다룬 논문 ([N. E. Wu, K. Zhou, and G. Salomon, “Control Reconfigurability of Linear Time-Invariant Systems,” p. 5, 2000.](https://www.sciencedirect.com/science/article/pii/S0005109800000807?via%3Dihub)) 을 참고하면 될듯

**Comment by hnlee77** [comment]
> LTI 시스템 버전을 다룬 논문 ([N. E. Wu, K. Zhou, and G. Salomon, “Control Reconfigurability of Linear Time-Invariant Systems,” p. 5, 2000.](https://www.sciencedirect.com/science/article/pii/S0005109800000807?via%3Dihub)) 을 참고하면 될듯

Good.
