### ISSUE TITLE
Gramian 계산하는 함수 작성

### ISSUE THREAD

**Issue by hnlee77** [JinraeKim/FTCTests.jl#61]
#58 의 비선형 시스템에 대한 empirical gramian을 계산하는 과정에 어려움을 겪고 있어서 선형 시스템에 대한 gramian을 계산하는 함수를 작성해보기로 함

**Comment by JinraeKim** [comment]
LTI 시스템 버전을 다룬 논문 ([N. E. Wu, K. Zhou, and G. Salomon, “Control Reconfigurability of Linear Time-Invariant Systems,” p. 5, 2000.](https://www.sciencedirect.com/science/article/pii/S0005109800000807?via%3Dihub)) 을 참고하면 될듯

**Comment by JinraeKim** [comment]
[ControlSystems.jl](https://juliacontrol.github.io/ControlSystems.jl/latest/lib/analysis/#ControlSystems.gram-Tuple{AbstractStateSpace,%20Symbol}) 에서 이미 해당 기능을 제공하고 있음
